
#### bait map create#####
#How to add text into column: f1$X1 = paste0('chr',f1$X1)

# dplyr join on multiple column, v2=v2 and v3=v3 coloumn
# example: test3= dplyr::inner_join(f1, ucsc, by = c("V2","V3"))


default = read.delim('Desktop/Digest_genome_DpnII_Arima_None_10-31-19_18-09-2020.txt',header = T,skip=1)

# read hicup digenst genome .ramp file(generated by chicagotool make)
HiCUP_digest = read.delim('Desktop/Digest_genome_DpnII_Arima_None_10-31-19_18-09-2020.txt.rmap',header = F)

#paste "chr" to 1st column
HiCUP_digest$V1 = paste0('chr',HiCUP_digest$V1)

write.table(HiCUP_digest,file = 'Desktop/chr_Hicup.ramp',quote = F,col.names = F,row.names = F,sep = '\t')


# read bed file with last 2 column
bait = read.delim('Desktop/seperated.txt',header = F)
# bait3 = unique(bait2)

#check final 

final = read.delim('Desktop/making_baitfile/Final_with_annotation.baitmap',header = F)

final2 = read.delim('Desktop/making_chicago_input/Final_with_annotation.bait.txt',header = F)

final2 = final2[,c(1:5)]
write.table(final2,file = 'Desktop/bait.baitmap',quote = F,col.names = F,row.names = F,sep = '\t')

# any() == are some value TRUE? 
# which() == which row is True?

## add chcaracter in empty cell
#sep = read.delim('Desktop/real_1377.baitmap_notyetaddnone',header = F)
#sep$V5 <- sub("^$", "none", sep$V5)
#f1$paste = paste0('chr',f1$bait_chr,':',f1$bait_start,'-',f1$bait_end)





##################
##################
###run Chicago####
##################




library(Chicago)
library(PCHiCdata)

#dataPath = system.file("extdata", package="PCHiCdata")
#testDesignDir = file.path(dataPath, "hg19TestDesign")

# cd 
#dir(testDesignDir)
#######
baitpath = file.path('Desktop/NewBaitmap_input/Test_bin_to_10X_10000_bait/')
dir(baitpath)
######
#testDataPath <- file.path(dataPath, "GMchinputFiles")
#dir(testDataPath)

######
target1 = file.path('~/Desktop/16000_10x')
target2 = file.path('~/Desktop/16000_10x')
target3 = file.path('~/Desktop/16000_10x')
target4 = file.path('~/Desktop/16000_10x')
#check input location
dir(target1)

### loading data  ###
file1 <- c(
  file.path(target1, "T24_1.chinput"),
  file.path(target1, "T24_2.chinput")
  #file.path(target1, "T241_3.chinput")
)

#####
file2 <- c(
  file.path(target2, "T24T_1.chinput"),
  file.path(target2, "T24T_2.chinput")
  #file.path(target2, "T24T_3.chinput")
)
#####
file3 <- c(
  file.path(target3, "SLT3_1.chinput"),
  file.path(target3, "SLT3_2.chinput")
  #file.path(target3, "SLT3_3.chinput")
)

#####
file4 <- c(
  file.path(target4, "FLT3_1.chinput"),
  file.path(target4, "FLT3_2.chinput")
  #file.path(target4, "FLT3_3.chinput")
)


cd <- setExperiment(designDir = baitpath)

### the place to modifying setting #####
print(settings(cd)$brownianNoise.subset)
##modify to desire value !! don't change max and min frgment size,
#need to rerun makeDesignfile.py if changed 
# example:
# cd <- modifySettings(cd, settings=list(brownianNoise.subset = 10))

### show default setting paprmeter 
defaultSettings()
### modify minNPerBait to 100
cd <- modifySettings(cd, settings=list(minNPerBait = 250))
print(settings(cd))
######

cd <- readAndMerge(files=file1, cd=cd)
###
cd <- readAndMerge(files=file2, cd=cd)
###
cd <- readAndMerge(files=file3, cd=cd)
###
cd <- readAndMerge(files=file4, cd=cd)

#ANALYSIS
cd <- chicagoPipeline(cd)


###### SAVE RESULT ####

outputDirectory = ("~/Desktop/OUT")
exportResults(cd, file.path(outputDirectory, "T24T_16000_10x"))

plottedBaitIDs <- plotBaits(cd, n=6)

plottedBaitIDs


?plotBaits


#loading .baitmap for finding the bait ID at colmn 4
bait.id = read.delim('Desktop/NewBaitmap_input/Test_bin_to_10X_bin_bowin/arima_hicup_digestmap_wo_chr.baitmap',header = F)
# plot specific bait location
plotBaits(cd,baits = 11685203
)


#### calling the result ####
#loading ibed file for refence
ibed.result = read.delim('Desktop/Rohit_setting_0222/T24_16xxx_rohit.ibed.txt',header = T)
ibed.result = subset(ibed.result, score > 5.00 & N_reads > 2)
#modified to UCSC

ibed.result$color = '#FF0000'
ibed.result$empty = '.'

ibed.result = ibed.result[,c(1,2,3,4,10,10,12,11,5,6,7,8,12,1,2,3,4,12)]

colnames(ibed.result) = c('bait_chr','bait_start','bait_end','bait_name','Score','Value',
'Exp',	'color',	'sourceChrom',	'sourceStart',	'sourceEnd',	'sourceName',
'sourceStrand',	'targetChrom',	 'targetStart',	  'targetEnd',	  'targetName',	'targetStrand')

ibed.result$Score = round(ibed.result$Score)

####
f1 = ibed.result

f1$bait_chr = paste0('chr',f1$bait_chr)
f1$sourceChrom = paste0('chr',f1$sourceChrom)
f1$targetChrom = paste0('chr',f1$targetChrom)
f1$color ="#A569BD"

## subset by chromosome
subset.chr = subset(f1,f1$bait_chr =='chr4' & f1$sourceChrom == 'chr4')
## change strong inteaction by color
chr =subset.chr

for (i in 1:nrow(chr)) {
  score <- chr[i, "Score"]
  if(score >= 15) {
    chr[i,8] = '#A569BD'
  } else if (score < 15 & score >= 10 ) {
    chr[i,8] = '#BB8FCE'}
  else if (score < 10 & score >= 7 ) {
    chr[i,8] = '#D2B4DE'
  }else{
    chr[i,8] = '#E8DAEF'
  }
}
## how to search odd number row 

for (i in 1:10) {
  if (i %% 2 ==1) print(i)
}


write.table(chr,file = 'Desktop/T24_chr4_Rohit.txt',quote = F,col.names = T,row.names = F,sep = '\t')











